// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAdJsgmpxoRN4aqg5vwEyliA6Zi5PBH3w',
    appId: '1:1022974399912:web:c37050b0029174b655b99d',
    messagingSenderId: '1022974399912',
    projectId: 'gps-traker-4de59',
    authDomain: 'gps-traker-4de59.firebaseapp.com',
    databaseURL: 'https://gps-traker-4de59-default-rtdb.firebaseio.com',
    storageBucket: 'gps-traker-4de59.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC9ddJ7gwMGrtMtqRvK2veJVETcsssa8Y',
    appId: '1:1022974399912:android:c3c0d1574abfc5c555b99d',
    messagingSenderId: '1022974399912',
    projectId: 'gps-traker-4de59',
    databaseURL: 'https://gps-traker-4de59-default-rtdb.firebaseio.com',
    storageBucket: 'gps-traker-4de59.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDruqVfmJeD3bRy2EH0YHslVvjMrKXPNew',
    appId: '1:1022974399912:ios:7f56bc48c7db59d855b99d',
    messagingSenderId: '1022974399912',
    projectId: 'gps-traker-4de59',
    databaseURL: 'https://gps-traker-4de59-default-rtdb.firebaseio.com',
    storageBucket: 'gps-traker-4de59.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDruqVfmJeD3bRy2EH0YHslVvjMrKXPNew',
    appId: '1:1022974399912:ios:eb541b759bbf04dd55b99d',
    messagingSenderId: '1022974399912',
    projectId: 'gps-traker-4de59',
    databaseURL: 'https://gps-traker-4de59-default-rtdb.firebaseio.com',
    storageBucket: 'gps-traker-4de59.appspot.com',
    iosBundleId: 'com.example.project.RunnerTests',
  );
}
